config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }
  
  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    get 'search' => 'homes#search', as: 'search'
    get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end
  
  
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }
  
  scope module: :public do
    root 'homes#top'
    
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    put 'customers/information' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/confirm' => 'orders#error'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show] do
      resources :cart_items, only: [:create, :update, :destroy]
    end
    resources :cart_items, only: [:index]
    resources :orders, only: [:new, :index, :create, :show]
    
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details

  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :destination, presence: true
  validates :name, presence: true
  validates :shipping_cost, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validates :grand_total, presence: true, :numericality => { :greater_than_or_equal_to => 0 }

  scope :ordered_today, -> { where(created_at: Time.current.at_beginning_of_day..Time.current.at_end_of_day) }

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_deposit: 0, confirm_deposit: 1, in_production: 2, preparing_shipment: 3, shipped: 4 }

  def get_shipping_informations_from(resource)
    class_name = resource.class.name
    if class_name == 'Customer' # resource: Customer
      self.postal_code = resource.postal_code
      self.destination = resource.address
      self.name = resource.full_name
    elsif class_name == 'Address' # resource: Address
      self.postal_code = resource.postal_code
      self.destination = resource.destination
      self.name = resource.name
    end
  end

  def create_order_details(customer)
    unless order_details.first
      cart_items = customer.cart_items.includes(:item)
      cart_items.each do |cart_item|
        item = cart_item.item
        OrderDetail.create!(
          order_id: id,
          item_id: item.id,
          price: item.with_tax_price,
          amount: cart_item.amount
        )
      end
      cart_items.destroy_all
    end
  end

  def are_all_details_completed?
    (order_details.completed.count == order_details.count) ? true : false
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_order, only: [:show, :update]

  def index
    if params[:customer_id]
      @customer = Customer.find(params[:customer_id])
      @orders = @customer.orders.page(params[:page]).reverse_order
    elsif params[:created_at] == "today"
      @orders = Order.ordered_today.includes(:customer).page(params[:page]).reverse_order
    else
      @orders = Order.includes(:customer).page(params[:page]).reverse_order
    end
  end

  def show
    @order_details = @order.order_details.includes(:item)
    @customer = @order.customer
  end

  def update
    if @order.update(order_params) && @order.confirm_deposit?
      @order.order_details.update_all(making_status: 1)
    end
    redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

  def ensure_order
    @order = Order.find(params[:id])
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<section class="inner">
	<h2 class="section-ttl">
		<% if params[:customer_id] %>
			<%= @customer.full_name %>さんの注文履歴一覧
		<% elsif params[:created_at] == "today" %>
			本日の注文履歴一覧
		<% else %>
			注文履歴一覧
		<% end %>
	</h2>
	<table class="admin_orders has_border">
		<thead>
			<tr>
				<th>注文日</th>
				<th>購入者</th>
				<th>注文個数</th>
				<th>総計</th>
				<th>注文ステータス</th>
			</tr>
		</thead>
		<tbody>
			<% @orders.each do |order| %>
				<tr>
					<td><%= link_to order.created_at.strftime("%Y/%m/%d %H:%M:%S"), admin_order_path(order), class: "underline" %></td>
					<td><%= link_to order.customer.full_name, admin_customer_path(order.customer) %></td>
					<td><%= order.order_details.sum(:amount) %></td>
					<td><%= order.grand_total %>円</td>
					<td class="text-center"><%= order.status_i18n %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<%= paginate @orders %>
</section>

app/views/admin/orders/show.html.erb
<section class="inner">
	<h2 class="section-ttl">注文履歴詳細</h2>
	<table class="order_info mb3 has_border">
		<caption class="fz18 text-left">注文情報</caption>
		<thead>
			<tr>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>注文日時</td>
				<td><%= @order.created_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
			</tr>
			<tr>
				<td>購入者</td>
				<td><%= link_to @customer.full_name, admin_customer_path(@customer), class: "underline" %></td>
			</tr>
			<tr>
				<td>配送先</td>
				<td>
					〒<%= @order.postal_code %><br>
					<%= @order.destination %><br>
					<%= @order.name %>
				</td>
			</tr>
			<tr>
				<td>支払い方法</td>
				<td><%= @order.payment_method_i18n %></td>
			</tr>
			<tr>
				<td>注文ステータス</td>
				<td>
					<%= form_with model:@order, url: admin_order_path(@order) do |f| %>
						<%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
						<%= f.submit "更新", class: "btn btn-primary" %>
					<% end %>
				</td>
			</tr>
		</tbody>
	</table>
	<div class="flex">
		<table class="admin_order_details mr2 has_border">
			<caption class="fz18 text-left">注文内容</caption>
			<thead>
				<tr>
					<th>商品名</th>
					<th>単価(税込)</th>
					<th>数量</th>
					<th>小計</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @order_details.each do |order_detail| %>
					<% item = order_detail.item %>
					<tr>
						<td><%= link_to item.name, admin_item_path(item) %></td>
						<td class="text-center"><%= order_detail.price %>円</td>
						<td class="text-center"><%= order_detail.amount %></td>
						<td class="text-center"><%= order_detail.subtotal %>円</td>
						<td>
							<%= form_with(model: order_detail, url: admin_order_order_detail_path(order_id: @order.id, id: order_detail.id)) do |f| %>
								<%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
								<%= f.submit "更新", class: "btn btn-primary" %>
							<% end %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>

		<table class="confirm_prices has_border">
			<caption class="fz18 text-left">請求情報</caption>
			<thead>
				<tr>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>送料</td>
					<td><%= @order.shipping_cost %>円</td>
				</tr>
				<tr>
					<td>商品合計</td>
					<td><%= @order_details.sum(&:subtotal) %>円</td>
				</tr>
				<tr>
					<td>総計</td>
					<td class="bold"><%= @order.grand_total %>円</td>
				</tr>
			</tbody>
		</table>
	</div>
</section>