config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }
  
  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    get 'search' => 'homes#search', as: 'search'
    get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end
  
  
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }
  
  scope module: :public do
    root 'homes#top'
    
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    put 'customers/information' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/confirm' => 'orders#error'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show] do
      resources :cart_items, only: [:create, :update, :destroy]
    end
    resources :cart_items, only: [:index]
    resources :orders, only: [:new, :index, :create, :show]
    
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  scope :only_active, -> { where(is_active: true) }

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_genre, only: [:show, :edit, :update]

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
  end

  def update
    if @genre.update(genre_params)
      unless @genre.is_active
        @genre.items.update_all(is_active: false)
      end
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :is_active)
  end

  def ensure_genre
    @genre = Genre.find(params[:id])
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_form.html.erb
<%= form_with model:genre, url: url do |f| %>
	<%= render 'layouts/error_messages', resource: genre %>
	<%= f.label :name, "ジャンル名:" %>
	<%= f.text_field :name %>
	<%= f.radio_button :is_active, true %>
	<%= f.label :is_active, "有効", class: "text-active" %>
	<%= f.radio_button :is_active, false %>
	<%= f.label :is_active, "無効", class: "text-invalid" %>
	<%= f.submit submit, class: "btn btn-primary ml2" %>
<% end %>

app/views/admin/genres/edit.html.erb
<section class="inner">
	<h2 class="section-ttl">ジャンル新規登録</h2>
  <%= render 'form', genre: @genre, url: admin_genre_path(@genre), submit: '更新' %>
</section>

app/views/admin/genres/index.html.erb
<section class="inner">
	<h2 class="section-ttl">ジャンル管理</h2>
	<div class="mb3">
		<h3>ジャンル新規登録</h3>
  	<%= render 'form', genre: @genre, url: admin_genres_path, submit: '登録' %>
	</div>
	<div class="mb3">
		<h3>ジャンル一覧</h3>
		<table class="genre_info has_border">
			<thead>
				<tr>
					<th>ジャンル名</th>
					<th>状態</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @genres.each do |genre| %>
					<tr>
						<td><%= link_to genre.name, admin_items_path(genre_id: genre.id), class: "underline" %></td>
						<td>
							<% if genre.is_active? %>
								<span class="text-active">有効</span>
							<% else %>
								<span class="text-invalid">無効</span>
							<% end %>
						</td>
						<td class="text-center"><%= link_to "編集", edit_admin_genre_path(genre), class: "btn btn-success" %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</section>