config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }
  
  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    get 'search' => 'homes#search', as: 'search'
    get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end
  
  
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }
  
  scope module: :public do
    root 'homes#top'
    
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    put 'customers/information' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/confirm' => 'orders#error'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show] do
      resources :cart_items, only: [:create, :update, :destroy]
    end
    resources :cart_items, only: [:index]
    resources :orders, only: [:new, :index, :create, :show]
    
  end
  
end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="<%= (admin_signed_in? ? "admin_header" : "" ) %>">
      <div class="header-content">
      <%= link_to 'NaganoCake', (admin_signed_in? ? admin_top_path : root_path ), class: "logo" %>
        <ul class="flex">
          <% if admin_signed_in? %>
            <li><%= link_to '商品一覧',  admin_items_path %></li>
            <li><%= link_to '会員一覧',  admin_customers_path %></li>
            <li><%= link_to '注文履歴一覧',  admin_orders_path %></li>
            <li><%= link_to 'ジャンル一覧',  admin_genres_path %></li>
            <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %></li>
          <% elsif customer_signed_in? %>
            <p>ようこそ、<%= current_customer.full_name %>さん!</p>
            <li><%= link_to 'マイページ', mypage_path %></li>
            <li><%= link_to '商品一覧', items_path %></li>
            <li><%= link_to 'カート', cart_items_path %></li>
            <li><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to '商品一覧', items_path %></li>
            <li><%= link_to '新規登録', new_customer_registration_path %></li>
            <li><%= link_to 'ログイン', new_customer_session_path %></li>
          <% end %>
        </ul>
        <% if admin_signed_in? %>
          <%= form_tag(admin_search_path, method: :get) do %>
            <%= text_field_tag "search[content]", "", :placeholder =>"会員: 姓,名,セイ,メイ / 商品: 商品名" %>
            <%= select_tag "search[model]", options_for_select({ "会員" => "customer", "商品" => "item" }) %>
            <%= select_tag "search[method]", options_for_select({ "部分一致" => "partial", "前方一致" => "forward", "後方一致" => "backward", "完全一致" => "perfect" }) %>
            <%= submit_tag '検索', class: "btn btn-primary" %>
          <% end %>
        <% end %>
        
      </div>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>Copyright © Infratop Inc. All Rights Reserved.</footer>
  </body>
</html>